variables:
  - group: status-endpoint
  - name: service_name
    value: gp-connect-access-record-structured-fhir
  - name: short_service_name
    value: gcarsf
  - name: service_base_path
    value: gp-connect-access-record-structured-fhir
