# This is an OpenAPI Specification (https://swagger.io/specification/)
# for gp-connect-access-record-structured-fhir owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'gp-connect-access-record-structured-fhir'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    Use this API to access structured information from a patient’s registered GP practice record. Structured information is patient data in a coded format that a consuming system can import and process.

    The API accesses GP principal supplier systems, provides a consistent interface and data model, and is brokered through [Spine](https://digital.nhs.uk/services/spine). 

    You can retrieve data from GP practice records for the following areas:

    - medications
    - allergies
    
    Data is available for the following clinical areas:

    - immunizations
    - consultations
    - problems
    - investigations
    - outbound referrals
    - diary entries
    - uncategorised data (other clinically coded items that are present in the record)
    
    These clinical areas are still in development; there is enough data to test, but it is subject to change as GP systems suppliers go through the development process.

    It does not include:

    - extended demographics information - for example, about carers
    - flags and alerts
    - templates
    - test requests
    
    Common use cases include:

    - access GP medications on admission to secondary care, reducing transcription errors
    - active checking of a patient's prescription in unscheduled care
    - out-of-hours GP accesses patient's medications, allergies and problems
    - midwife views patient record before visiting a patient
    - community cardiac nurse accesses GP record before visiting a patient
    
    
    For more details, see the [GP Connect Access Record: Structured specification](https://developer.nhs.uk/apis/gpconnect-1-5-1/accessrecord_structured.html).

    You cannot currently use this API to:

    - create patient-facing views of a medical record
    - create reports for secondary use, such as care planning
    - write back to the GP record
    
    
    ## Retrieving documents
    
    To retrieve documents from a patient’s registered GP practice, use [GP Connect Access Document - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-access-document-fhir). After you've found the relevant document references within Access Record returns, use GP Connect Access Document to retrieve the documents. All documents can be requested separately.


    ## Who can use this API
    To be completed.
    ## Related APIs
    To be completed.
    ## API status and roadmap
    To be completed.
    ## Service level
    To be completed.
    ## Technology
    To be completed.
    ## Network access
    To be completed.
    ## Security and authorisation
    To be completed.
    ## Environments and testing
    To be completed.
    ## Onboarding
    To be completed.
  contact:
    name: 'gp-connect-access-record-structured-fhir API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/gp-connect-access-record-structured-fhir'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/gp-connect-access-record-structured-fhir'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/gp-connect-access-record-structured-fhir'
    description: Production environment.
paths: {}
